### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by bdebowski** [Aviana/YaHT#19] opened 2019-08-30 16:10 UTC
just added this addon and it looks like the bar is in an endless loop of filling white, depleteing red, filling white, depleteing red, etc.  the behaviour does not change whether i move or stand still or attack.
Did blizzard break your addon?

**Comment by iamMeshi** [comment] 2019-08-31 05:40
Installed this morning and seeing this behavior as well. From looking at the guides for this it doesn't seem like it should be doing anything when not in combat, however for me it keeps looping.

**Comment by Aviana** [comment] 2019-08-31 10:57
Duplicate of #15

**Closed as completed by Aviana** 2019-08-31 10:57 UTC
